---
# tasks file for getPackages
- name: Get installed packages
  become: yes
  command: dpkg --get-selections
  register: dpkg_output

- name: Display installed packages
  debug:
    var: dpkg_output.stdout_lines

