---
# tasks file for getPackages
- name: Get installed packages
  become: yes
  command: dpkg --get-selections
  register: dpkg_output

- name: Display installed packages
  debug:
    var: dpkg_output.stdout_lines

# - name: Get package installation dates
#   become: yes
#   shell: dpkg-query -W -f='${Package} ${Version} ${Status} ${installtime:Date}\n'
#   register: dpkg_dates_output

# - name: Display package installation dates
#   debug:
#     var: dpkg_dates_output.stdout_lines








# - name: Get package information including installation dates
#   become: yes
#   command: dpkg-query -W -f='${Package},${Version},${Status},${installtime:Date}\n'
#   register: dpkg_output1

# - name: Get package installation dates from APT logs
#   become: yes
#   shell: zgrep -B1 'install' /var/log/apt/history.log*
#   with_items: "{{ dpkg_output1.stdout_lines | map('split', ',') | map('first') }}"
#   register: apt_logs_output



# - name: Display package installation dates
#   debug:
#     var: apt_logs_output.stdout_lines















- name: Get package information
  become: yes
  command: dpkg-query -W -f='${Package}\n'
  register: dpkg_output1

# - name: Get package installation dates from APT logs
#   become: yes
#   shell: zgrep -B100 'install {{ item }}' /var/log/apt/history.log* | grep -E ".*Date:.*" | awk '{ $3=""; print $0 }'
#   with_items: "{{ dpkg_output1.stdout_lines }}"
#   register: apt_logs_output


# - name: Get package installation dates from APT logs
#   become: yes
#   shell: zgrep -B100 'install {{ item }}' /var/log/apt/history.log* | grep -E ".*Date:.*" | awk '{ $3=""; print $0 }'
#   with_items: "{{ dpkg_output1.stdout_lines }}"
#   register: apt_logs_output

# - name: Display package installation dates
#   debug:
#     msg: "Package: {{ item.item }}, Date: {{ item.stdout | regex_replace('Start-Date: ', '') }}"
#   with_items: "{{ apt_logs_output.results }}"


- name: Get package installation dates from APT logs
  become: yes
  shell: >
    zgrep -B100 'install {{ item }}' /var/log/apt/history.log* | awk '{ $3=""; print $0 }'
  with_items: "{{ dpkg_output1.stdout_lines }}"
  register: apt_logs_output



- name: Display package installation dates
  debug:
    msg: "Package: {{ item.item }}, Date: {{ item.stdout | regex_replace('Start-Date: ', '') }}"
  with_items: "{{ apt_logs_output.results }}"

